import { CARD_MARKET_VALUES } from './rouletteConfig';
import type { Card, CardDesign } from '../types/roulette.types';

const CREATED_AT = '2026-07-03T00:00:00.000Z';

type CardContent = Omit<Card, 'design' | 'marketValue' | 'number'>;

const CARD_DESIGN_BY_ID: Record<string, CardDesign> = {
  'common-morning-spark': {
    gradient: ['#262626', 'rgba(202,255,0,0.18)', '#121212'],
    accent: '#CAFF00',
    motif: 'spark',
    glyph: 'M1',
    stripeAngle: -26,
    seed: 11,
  },
  'common-clean-slate': {
    gradient: ['#1C1C1C', 'rgba(255,255,255,0.14)', '#000000'],
    accent: '#A8A8A8',
    motif: 'slate',
    glyph: 'CS',
    stripeAngle: 18,
    seed: 17,
  },
  'common-two-minute-start': {
    gradient: ['#121212', 'rgba(0,149,246,0.20)', '#262626'],
    accent: '#0095F6',
    motif: 'bolt',
    glyph: '02',
    stripeAngle: -12,
    seed: 23,
  },
  'common-soft-deadline': {
    gradient: ['#262626', 'rgba(255,149,0,0.17)', '#121212'],
    accent: '#FF9500',
    motif: 'clock',
    glyph: 'DL',
    stripeAngle: 34,
    seed: 29,
  },
  'common-focus-window': {
    gradient: ['#000000', 'rgba(0,216,255,0.16)', '#1C1C1C'],
    accent: '#00D8FF',
    motif: 'frame',
    glyph: 'FW',
    stripeAngle: -38,
    seed: 31,
  },
  'common-small-proof': {
    gradient: ['#1C1C1C', 'rgba(255,53,0,0.18)', '#121212'],
    accent: '#FF3500',
    motif: 'receipt',
    glyph: 'SP',
    stripeAngle: 24,
    seed: 37,
  },
  'common-vote-check': {
    gradient: ['#262626', 'rgba(0,216,255,0.13)', '#000000'],
    accent: '#00D8FF',
    motif: 'vote',
    glyph: 'VC',
    stripeAngle: -6,
    seed: 41,
  },
  'common-late-save': {
    gradient: ['#121212', 'rgba(255,149,0,0.20)', '#262626'],
    accent: '#FF9500',
    motif: 'save',
    glyph: 'LS',
    stripeAngle: 42,
    seed: 43,
  },
  'common-quiet-yes': {
    gradient: ['#000000', 'rgba(202,255,0,0.12)', '#1C1C1C'],
    accent: '#CAFF00',
    motif: 'signal',
    glyph: 'QY',
    stripeAngle: -44,
    seed: 47,
  },
  'common-streak-kindling': {
    gradient: ['#262626', 'rgba(255,53,0,0.16)', '#121212'],
    accent: '#FF3500',
    motif: 'flame',
    glyph: 'SK',
    stripeAngle: 10,
    seed: 53,
  },
  'common-proof-pulse': {
    gradient: ['#1C1C1C', 'rgba(0,216,255,0.20)', '#000000'],
    accent: '#00D8FF',
    motif: 'pulse',
    glyph: 'PP',
    stripeAngle: -20,
    seed: 59,
  },
  'common-commit-chip': {
    gradient: ['#121212', 'rgba(157,111,255,0.18)', '#262626'],
    accent: '#9D6FFF',
    motif: 'chip',
    glyph: 'CC',
    stripeAngle: 28,
    seed: 61,
  },
  'common-early-signal': {
    gradient: ['#262626', 'rgba(0,149,246,0.16)', '#121212'],
    accent: '#0095F6',
    motif: 'route',
    glyph: 'ES',
    stripeAngle: -32,
    seed: 67,
  },
  'common-restart-line': {
    gradient: ['#000000', 'rgba(255,255,255,0.10)', '#262626'],
    accent: '#FFFFFF',
    motif: 'line',
    glyph: 'RL',
    stripeAngle: 6,
    seed: 71,
  },
  'common-checkpoint': {
    gradient: ['#1C1C1C', 'rgba(202,255,0,0.14)', '#000000'],
    accent: '#CAFF00',
    motif: 'peak',
    glyph: 'CP',
    stripeAngle: -48,
    seed: 73,
  },
  'rare-seven-day-mark': {
    gradient: ['#121212', 'rgba(0,216,255,0.30)', 'rgba(202,255,0,0.12)'],
    accent: '#00D8FF',
    motif: 'flame',
    glyph: '7D',
    stripeAngle: 16,
    seed: 79,
  },
  'rare-public-stake': {
    gradient: ['#262626', 'rgba(157,111,255,0.30)', '#000000'],
    accent: '#9D6FFF',
    motif: 'chip',
    glyph: 'PS',
    stripeAngle: -18,
    seed: 83,
  },
  'rare-proof-runner': {
    gradient: ['#000000', 'rgba(0,216,255,0.26)', 'rgba(255,255,255,0.10)'],
    accent: '#00D8FF',
    motif: 'route',
    glyph: 'PR',
    stripeAngle: 38,
    seed: 89,
  },
  'rare-crowd-tilt': {
    gradient: ['#121212', 'rgba(0,149,246,0.28)', 'rgba(255,149,0,0.12)'],
    accent: '#0095F6',
    motif: 'vote',
    glyph: 'CT',
    stripeAngle: -40,
    seed: 97,
  },
  'rare-reputation-rise': {
    gradient: ['#1C1C1C', 'rgba(202,255,0,0.22)', 'rgba(0,216,255,0.12)'],
    accent: '#CAFF00',
    motif: 'peak',
    glyph: 'RR',
    stripeAngle: 12,
    seed: 101,
  },
  'rare-deadline-discipline': {
    gradient: ['#262626', 'rgba(255,149,0,0.30)', '#121212'],
    accent: '#FF9500',
    motif: 'clock',
    glyph: 'DD',
    stripeAngle: -24,
    seed: 103,
  },
  'rare-accountability-loop': {
    gradient: ['#000000', 'rgba(0,216,255,0.22)', 'rgba(157,111,255,0.14)'],
    accent: '#00D8FF',
    motif: 'pulse',
    glyph: 'AL',
    stripeAngle: 30,
    seed: 107,
  },
  'ultra-legend-streak': {
    gradient: ['#000000', 'rgba(255,149,0,0.42)', 'rgba(202,255,0,0.28)'],
    accent: '#CAFF00',
    motif: 'crown',
    glyph: 'LS',
    stripeAngle: -14,
    seed: 113,
  },
  'ultra-proof-master': {
    gradient: ['#121212', 'rgba(0,216,255,0.42)', 'rgba(255,255,255,0.18)'],
    accent: '#00D8FF',
    motif: 'crown',
    glyph: 'PM',
    stripeAngle: 26,
    seed: 127,
  },
  'ultra-volt-finish': {
    gradient: ['#000000', 'rgba(202,255,0,0.45)', 'rgba(255,53,0,0.22)'],
    accent: '#CAFF00',
    motif: 'bolt',
    glyph: 'VF',
    stripeAngle: -36,
    seed: 131,
  },
};

const CARD_CONTENT: CardContent[] = [
  {
    id: 'common-morning-spark',
    name: 'Morning Spark',
    description: 'A first small promise made before the feed wakes up.',
    rarity: 'common',
    imageUrl: 'drift://cards/morning-spark',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-clean-slate',
    name: 'Clean Slate',
    description: 'A reset badge for the day after a hard miss.',
    rarity: 'common',
    imageUrl: 'drift://cards/clean-slate',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-two-minute-start',
    name: 'Two-Minute Start',
    description: 'Proof that momentum does not need a ceremony.',
    rarity: 'common',
    imageUrl: 'drift://cards/two-minute-start',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-soft-deadline',
    name: 'Soft Deadline',
    description: 'A quiet timer that turns vague plans into motion.',
    rarity: 'common',
    imageUrl: 'drift://cards/soft-deadline',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-focus-window',
    name: 'Focus Window',
    description: 'A narrow block of time protected from excuses.',
    rarity: 'common',
    imageUrl: 'drift://cards/focus-window',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-small-proof',
    name: 'Small Proof',
    description: 'A tiny receipt that still counts when the day is messy.',
    rarity: 'common',
    imageUrl: 'drift://cards/small-proof',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-vote-check',
    name: 'Vote Check',
    description: 'The crowd looked once and the signal got sharper.',
    rarity: 'common',
    imageUrl: 'drift://cards/vote-check',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-late-save',
    name: 'Late Save',
    description: 'A deadline met with minutes left on the clock.',
    rarity: 'common',
    imageUrl: 'drift://cards/late-save',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-quiet-yes',
    name: 'Quiet Yes',
    description: 'No speech, no drama, just the next correct action.',
    rarity: 'common',
    imageUrl: 'drift://cards/quiet-yes',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-streak-kindling',
    name: 'Streak Kindling',
    description: 'The first mark in a chain that might become serious.',
    rarity: 'common',
    imageUrl: 'drift://cards/streak-kindling',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-proof-pulse',
    name: 'Proof Pulse',
    description: 'A clean upload, a clear timestamp, a public finish.',
    rarity: 'common',
    imageUrl: 'drift://cards/proof-pulse',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-commit-chip',
    name: 'Commit Chip',
    description: 'A small token for putting a stake in the ground.',
    rarity: 'common',
    imageUrl: 'drift://cards/commit-chip',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-early-signal',
    name: 'Early Signal',
    description: 'The first public nudge before a drift gains speed.',
    rarity: 'common',
    imageUrl: 'drift://cards/early-signal',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-restart-line',
    name: 'Restart Line',
    description: 'A line drawn for another attempt without the noise.',
    rarity: 'common',
    imageUrl: 'drift://cards/restart-line',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'common-checkpoint',
    name: 'Checkpoint',
    description: 'A pause that records progress before the next climb.',
    rarity: 'common',
    imageUrl: 'drift://cards/checkpoint',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-seven-day-mark',
    name: 'Seven-Day Mark',
    description: 'A full week of showing up when novelty faded.',
    rarity: 'rare',
    imageUrl: 'drift://cards/seven-day-mark',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-public-stake',
    name: 'Public Stake',
    description: 'A visible promise with enough weight to change behavior.',
    rarity: 'rare',
    imageUrl: 'drift://cards/public-stake',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-proof-runner',
    name: 'Proof Runner',
    description: 'The finish arrives fast because the route was clear.',
    rarity: 'rare',
    imageUrl: 'drift://cards/proof-runner',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-crowd-tilt',
    name: 'Crowd Tilt',
    description: 'A close vote turns pressure into useful attention.',
    rarity: 'rare',
    imageUrl: 'drift://cards/crowd-tilt',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-reputation-rise',
    name: 'Reputation Rise',
    description: 'Consistency leaves a visible mark on the profile.',
    rarity: 'rare',
    imageUrl: 'drift://cards/reputation-rise',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-deadline-discipline',
    name: 'Deadline Discipline',
    description: 'The clock stayed loud enough to keep the promise real.',
    rarity: 'rare',
    imageUrl: 'drift://cards/deadline-discipline',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'rare-accountability-loop',
    name: 'Accountability Loop',
    description: 'Commit, vote, prove, repeat until it feels normal.',
    rarity: 'rare',
    imageUrl: 'drift://cards/accountability-loop',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'ultra-legend-streak',
    name: 'Legend Streak',
    description: 'A run long enough that discipline starts looking inevitable.',
    rarity: 'ultra_rare',
    imageUrl: 'drift://cards/legend-streak',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'ultra-proof-master',
    name: 'Proof Master',
    description: 'Every receipt lands clean, and the archive speaks for itself.',
    rarity: 'ultra_rare',
    imageUrl: 'drift://cards/proof-master',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
  {
    id: 'ultra-volt-finish',
    name: 'Volt Finish',
    description: 'The rare close where pressure turns into a perfect final push.',
    rarity: 'ultra_rare',
    imageUrl: 'drift://cards/volt-finish',
    isCaseExclusive: false,
    createdAt: CREATED_AT,
  },
];

export const ROULETTE_CARDS: Card[] = CARD_CONTENT.map((card, index) => ({
  ...card,
  number: index + 1,
  marketValue: CARD_MARKET_VALUES[card.rarity],
  design: CARD_DESIGN_BY_ID[card.id],
}));

export const ROULETTE_CARD_BY_ID = ROULETTE_CARDS.reduce<Record<string, Card>>((map, card) => {
  map[card.id] = card;
  return map;
}, {});

export const MAIN_ROULETTE_CARD_IDS = ROULETTE_CARDS.filter((card) => !card.isCaseExclusive).map((card) => card.id);

export function getCardsByIds(ids: string[]): Card[] {
  return ids.map((id) => ROULETTE_CARD_BY_ID[id]).filter((card): card is Card => Boolean(card));
}
