import type { CardCase } from '../types/roulette.types';

export const ROULETTE_CASES: CardCase[] = [
  {
    id: 'streak-forge',
    title: 'Streak Forge',
    description: 'A focused case for users who keep a seven-day promise chain alive.',
    unlockType: 'achievement',
    achievementId: 'streak_7',
    cardPool: [
      'common-streak-kindling',
      'common-checkpoint',
      'common-proof-pulse',
      'rare-seven-day-mark',
      'rare-accountability-loop',
      'ultra-legend-streak',
    ],
    isUnlocked: false,
    isOpened: false,
    design: {
      gradient: ['#121212', 'rgba(255,53,0,0.32)', 'rgba(255,149,0,0.18)'],
      accent: '#FF3500',
      glyph: 'SF',
      patternAngle: -22,
    },
  },
  {
    id: 'proof-vault',
    title: 'Proof Vault',
    description: 'A purchasable vault tuned toward proof, deadlines, and reputation cards.',
    unlockType: 'purchase',
    price: 2,
    cardPool: [
      'common-small-proof',
      'common-proof-pulse',
      'common-late-save',
      'rare-proof-runner',
      'rare-deadline-discipline',
      'rare-reputation-rise',
      'ultra-proof-master',
      'ultra-volt-finish',
    ],
    isUnlocked: true,
    isOpened: false,
    design: {
      gradient: ['#000000', 'rgba(0,216,255,0.34)', 'rgba(255,255,255,0.12)'],
      accent: '#00D8FF',
      glyph: 'PV',
      patternAngle: 18,
    },
  },
  {
    id: 'crowd-signal',
    title: 'Crowd Signal',
    description: 'A case for users who turn votes and pressure into useful public feedback.',
    unlockType: 'achievement',
    achievementId: 'vote_signal_25',
    cardPool: [
      'common-vote-check',
      'common-early-signal',
      'common-quiet-yes',
      'rare-crowd-tilt',
      'rare-public-stake',
      'rare-accountability-loop',
      'ultra-volt-finish',
    ],
    isUnlocked: false,
    isOpened: false,
    design: {
      gradient: ['#1C1C1C', 'rgba(0,149,246,0.34)', 'rgba(157,111,255,0.16)'],
      accent: '#0095F6',
      glyph: 'CS',
      patternAngle: -34,
    },
  },
  {
    id: 'deadline-cache',
    title: 'Deadline Cache',
    description: 'A paid cache with timer, save, and discipline cards weighted into the pool.',
    unlockType: 'purchase',
    price: 3,
    cardPool: [
      'common-soft-deadline',
      'common-late-save',
      'common-focus-window',
      'common-two-minute-start',
      'rare-deadline-discipline',
      'rare-proof-runner',
      'ultra-proof-master',
    ],
    isUnlocked: true,
    isOpened: false,
    design: {
      gradient: ['#262626', 'rgba(255,149,0,0.38)', 'rgba(202,255,0,0.12)'],
      accent: '#FF9500',
      glyph: 'DC',
      patternAngle: 26,
    },
  },
  {
    id: 'legend-cache',
    title: 'Legend Cache',
    description: 'A high-reputation case built around rare finishers and profile-worthy cards.',
    unlockType: 'achievement',
    achievementId: 'reputation_75',
    cardPool: [
      'rare-seven-day-mark',
      'rare-reputation-rise',
      'rare-public-stake',
      'rare-accountability-loop',
      'ultra-legend-streak',
      'ultra-proof-master',
      'ultra-volt-finish',
    ],
    isUnlocked: false,
    isOpened: false,
    design: {
      gradient: ['#000000', 'rgba(202,255,0,0.40)', 'rgba(255,149,0,0.24)'],
      accent: '#CAFF00',
      glyph: 'LC',
      patternAngle: -12,
    },
  },
];

export const ROULETTE_CASE_BY_ID = ROULETTE_CASES.reduce<Record<string, CardCase>>((map, cardCase) => {
  map[cardCase.id] = cardCase;
  return map;
}, {});
